import { Event } from "./types";

export const events: Event[] = [
    {
        id: "1",
        title: "Group Dance",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676738761912",
        description: "Group Dance is a dance competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "yellow",
    },
    {
        id: "2",
        title: "Street Play",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/3.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739267473",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "orange",
    },
    {
        id: "3",
        title: "Stand Up Comedy",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/4.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "green",
    },
    {
        id: "4",
        title: "War of DJ",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "lavender",
    },
    {
        id: "5",
        title: "Solo Dance",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "yellow",
    },
    {
        id: "6",
        title: "Solo Singing ",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "green",
    },
    {
        id: "7",
        title: "Rap Battle",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "orange",
    },
    {
        id: "8",
        title: "War of Bands",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "lavender",
    },
    {
        id: "9",
        title: "Beat Boxing",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "yellow",
    },
    {
        id: "10",
        title: "Advertise your product",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "orange",
    },
    {
        id: "11",
        title: "Childhood Snack Auction",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "green",
    },
    {
        id: "12",
        title: "Youtube Exchange",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "lavender",
    },
    {
        id: "13",
        title: "Swipe right Swipe left",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "yellow",
    },
    {
        id: "14",
        title: "Storage Wars",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "green",
    },
    {
        id: "15",
        title: "Donation Drive",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "orange",
    },
    {
        id: "16",
        title: "Treasure Hunt",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "lavender",
    },
    {
        id: "17",
        title: "Origami Workshop",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "yellow",
    },
    {
        id: "18",
        title: "T-shirt Painting",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "orange",
    },
    {
        id: "10",
        title: "Glitz & Glam",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "green",
    },
    {
        id: "6",
        title: "A day at sattva",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "lavender",
    },
    {
        id: "1",
        title: "Valorant",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "yellow",
    },
    {
        id: "2",
        title: "Glow TT",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "green",
    },
    {
        id: "3",
        title: "foot pool",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "orange",
    },
    {
        id: "4",
        title: "Fifa",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "lavender",
    },
    {
        id: "1",
        title: "Dance Workshop",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "yellow",
    },
    {
        id: "2",
        title: "Self Defence",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "orange",
    },
    {
        id: "3",
        title: "Origami",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "green",
    },
    {
        id: "4",
        title: "The Covert to Polished Carrer",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "lavender",
    },
    {
        id: "5",
        title: "GRE & CAT Prep",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "yellow",
    },
    {
        id: "1",
        title: "Cards Aganist Sattva",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "green",
    },
    {
        id: "2",
        title: "Me. & Mrs. Sattva",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "orange",
    },
    {
        id: "3",
        title: "Memery",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories:"Informals",
        color: "lavender",
    },
    {
        id: "4",
        title: "Dares and Snakes",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "yellow",
    },
    {
        id: "5",
        title: "Speed Dating with Buzzer",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "green",
    },
    {
        id: "6",
        title: "Spin The Wheel Dares",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "orange",
    },
    {
        id: "7",
        title: "Fish Tank",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "lavender",
    },
    {
        id: "8",
        title: "Gartic Phone",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "yellow",
    },
]