import { Event } from "./types";

export const events: Event[] = [
    {
        id: "1",
        title: "Group Dance",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676738761912",
        description: "Group Dance is a dance competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "yellow",
    },
    {
        id: "2",
        title: "Street Play",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/3.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739267473",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "orange",
    },
    {
        id: "3",
        title: "Stand Up Comedy",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/4.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "green",
    },
    {
        id: "4",
        title: "War of DJ",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263906",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "lavender",
    },
    {
        id: "5",
        title: "Solo Dance",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/6.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739267318",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "yellow",
    },
    {
        id: "6",
        title: "Solo Singing ",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/7.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263937",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "green",
    },
    {
        id: "7",
        title: "Rap Battle",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/8.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739263921",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "orange",
    },
    {
        id: "8",
        title: "War of Bands",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/9.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739267465",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "lavender",
    },
    {
        id: "9",
        title: "Beat Boxing",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva/10.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676739264005",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Performing Arts",
        color: "yellow",
    },
    {
        id: "10",
        title: "Advertise your product",
        day: 1,
        href: "https://forms.gle/KqFf7GraNpMxmwnj6",
        link: "https://forms.gle/KqFf7GraNpMxmwnj6",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Management/2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676741810697",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "orange",
    },
    {
        id: "11",
        title: "Childhood Snack Auction",
        day: 1,
        href: "https://forms.gle/r2SuCGjFfnDc2yZ26",
        link: "https://forms.gle/r2SuCGjFfnDc2yZ26",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Management/3.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676741810711",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "green",
    },
    {
        id: "12",
        title: "Youtube Exchange",
        day: 1,
        href: "https://forms.gle/wTNSnPJnmKpqujFBA",
        link: "https://forms.gle/wTNSnPJnmKpqujFBA",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Management/4.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676741810612",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "lavender",
    },
    {
        id: "13",
        title: "Swipe right Swipe left",
        day: 1,
        href: "https://forms.gle/WY2nWr3nYYFjJXeA8",
        link: "https://forms.gle/WY2nWr3nYYFjJXeA8",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Management/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676741810623",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "yellow",
    },
    {
        id: "14",
        title: "Storage Wars",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Management/6.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676741810652",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Management",
        color: "green",
    },
    {
        id: "15",
        title: "Donation Drive",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Management/dd.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676809709468",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "orange",
    },
    {
        id: "16",
        title: "Treasure Hunt",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Socials/2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676804320596",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "lavender",
    },
    {
        id: "17",
        title: "Origami Workshop",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Socials/4.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676804320558",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "yellow",
    },
    {
        id: "18",
        title: "T-shirt Painting",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Socials/5.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676804320452",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "orange",
    },
    {
        id: "19",
        title: "Glitz & Glam",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Socials/6.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676804320484",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "green",
    },
    {
        id: "20",
        title: "A day at sattva",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Socials/2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676804320596",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Socials",
        color: "lavender",
    },
    {
        id: "21",
        title: "Valorant",
        day: 1,
        href: "https://forms.gle/5TKYqiETf8Z6sxQw5",
        link: "https://forms.gle/5TKYqiETf8Z6sxQw5",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Sports/1.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676808357922",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "yellow",
    },
    {
        id: "22",
        title: "Glow TT",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Sports/3.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676808357760",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "green",
    },
    {
        id: "23",
        title: "foot pool",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Sports/4.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676808358128",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "orange",
    },
    {
        id: "24",
        title: "Fifa",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Sports/2.jpg?ik-sdk-version=javascript-1.4.3&updatedAt=1676808357432",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Sports",
        color: "lavender",
    },
    {
        id: "25",
        title: "Dance Workshop",
        day: 1,
        href: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        link: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Workshops/3.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808608558",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "yellow",
    },
    {
        id: "26",
        title: "Self Defence",
        day: 1,
        href: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        link: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Workshops/2.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808608740",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "orange",
    },
    {
        id: "27",
        title: "Origami",
        day: 1,
        href: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        link: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Workshops/1.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808609865",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "green",
    },
    {
        id: "28",
        title: "The Covert to Polished Carrer",
        day: 1,
        href: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        link: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Workshops/4.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808608996",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "lavender",
    },
    {
        id: "29",
        title: "GRE & CAT Prep",
        day: 1,
        href: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        link: "https://forms.gle/zY6UjAM9pm1wFcsm9",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Workshops/5.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808610040",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Workshops",
        color: "yellow",
    },
    {
        id: "30",
        title: "Cards Aganist Sattva",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/8.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676809121062",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "green",
    },
    {
        id: "31",
        title: "Me. & Mrs. Sattva",
        day: 1,
        href: "https://forms.gle/WQCJtYZSbJabALXZ7",
        link: "https://forms.gle/WQCJtYZSbJabALXZ7",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/3.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808952690",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "orange",
    },
    {
        id: "32",
        title: "Memery",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/2.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808955455",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories:"Informals",
        color: "lavender",
    },
    {
        id: "33",
        title: "Dares and Snakes",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/1.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808954377",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "yellow",
    },
    {
        id: "34",
        title: "Speed Dating with Buzzer",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/7.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808952973",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "green",
    },
    {
        id: "35",
        title: "Spin The Wheel Dares",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/4.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808954723",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "orange",
    },
    {
        id: "36",
        title: "Fish Tank",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/5.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808953873",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "lavender",
    },
    {
        id: "37",
        title: "Gartic Phone",
        day: 1,
        href: "https://hacktoberfest.digitalocean.com/",
        link: "https://hacktoberfest.digitalocean.com/",
        image: "https://ik.imagekit.io/zaidmukaddam/Sattva-Informals/6.png?ik-sdk-version=javascript-1.4.3&updatedAt=1676808952812",
        description: "Street Play is a competition where teams of 4-6 members compete against each other. The teams will be judged on their creativity, synchronization, and overall performance.",
        categories: "Informals",
        color: "yellow",
    },
]